language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
      
services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - pip install coveralls
  - pip install future
  - pip install pysatCDF >/dev/null

# command to install dependencies
install:
  - source activate test-environment
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install

# command to run tests
script:
 - nosetests -vs --with-coverage --cover-package=pysat

after_success:
 - coveralls
